version: '2'

x-webclient-service: &webclient-service
  image: yarra-webclient:latest
  environment:
    PYTHONUNBUFFERED: 'true'
  depends_on:
    - postgres
    - redis
  restart: always
  volumes:
    - 'data:/app/webclient/data'
    - '/media/archive:/archive'
   
services:
  yarra-webclient:
    <<: *webclient-service
    depends_on:
      - celery
    expose:
     - "8000"
  celery:
    <<: *webclient-service
    command: celery worker --app=app.celery --concurrency=2 --loglevel=INFO
    depends_on:
      - redis
  nginx:
    image: yarranyu/webclient-nginx:latest
    ports:
     - "6060:8080"
    depends_on: 
      - yarra-webclient
    links:
     - yarra-webclient:web
  tasker:
      image: strm/tasker
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
           configuration: |
               logging:
                  level:
                    ROOT: WARN
                    org.springframework.web: WARN
               schedule:
                   - every: day
                     task: indexer
               tasks:
                   docker:
                       - name: indexer
                         image: yarranyu/archive-indexer:0.1b11
                         entrypoint: ./YASIndexer
                         volumes:
                          - 'data:/data'
                          - '/media/archive:/archive'
  redis:
    image: redis
volumes:
  data:
