version: '2'

x-webclient-service: &webclient-service
  image: yarra-webclient:latest
  environment:
    PYTHONUNBUFFERED: 'true'
    YARRA_ARCHIVE_UPLOAD: 'true'
  volumes:
    - 'data:/app/webclient/data'
    - '/media/archive:/archive'   # disable this if you don't have a raw data archive
services:
  yarra-webclient:
    <<: *webclient-service
    depends_on:
      - celery
    expose:
      - "8000"
  celery:
    <<: *webclient-service
    command: celery worker --app=app.celery --concurrency=2 --loglevel=WARN
    depends_on:
      - redis
  celery-beat:
    <<: *webclient-service
    command: celery beat --app=app.celery --loglevel=WARN
    depends_on:
      - redis
  nginx:
    image: yarranyu/webclient-nginx:latest
    ports:
      - "6060:8080"
    depends_on: 
      - yarra-webclient
    links:
      - yarra-webclient:web
  redis:
    image: redis
    expose: 
      - "6739"
  archive-index-task: # disable this if you don't have a raw data archive
      image: strm/tasker 
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
           configuration: |
               logging:
                  level:
                    ROOT: WARN
                    org.springframework.web: WARN
               schedule:
                   - every: day
                     task: indexer
               tasks:
                   docker:
                       - name: indexer
                         image: yarranyu/archive-indexer:0.1b11
                         entrypoint: ./YASIndexer
                         volumes:
                          - 'data:/data'
                          - '/media/archive:/archive'
volumes:
  data:
