version: '2'

services:
  yarra-webclient:
    image: yarra-webclient:latest
    build: .
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - 'data:/app/webclient/data'
      - '/media/archive:/archive'
    command: >
      gunicorn -b 0.0.0.0:6060
        --access-logfile -
        --reload
        "app:app"
    expose: 
        - "6060"
    depends_on:
      - celery
  nginx:
    depends_on: 
      - yarra-webclient
    image: nginxinc/nginx-unprivileged
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./webclient/files:/usr/src/app/static
    ports:
     - "6060:6060"
    links:
     - yarra-webclient:web
  celery:
    image: yarra-webclient:latest
    build: .
    command: celery worker --app=app.celery --concurrency=2 --loglevel=INFO
    volumes:
      - 'data:/app/webclient/data'
      - '/media/archive:/archive'
    depends_on:
      - redis
  tasker:
      image: strm/tasker
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
           configuration: |
               logging:
                  level:
                    ROOT: WARN
                    org.springframework.web: WARN
               schedule:
                   - every: day
                     task: indexer
               tasks:
                   docker:
                       - name: indexer
                         image: yarra-indexer:latest
                         entrypoint: ./YASIndexer
                         volumes:
                          - 'data:/data'
                          - '/media/archive:/archive'
  redis:
    image: redis
volumes:
  data: